# Pandas

# File reading and Write operation

In [12]:
import pandas as pd
import numpy as np
np.set_printoptions(precision=4)

In [13]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
pwd()

'C:\\Users\\Raushan'

In [15]:
draft1=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex1.csv')
draft1

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [16]:
type(draft1)

pandas.core.frame.DataFrame

In [17]:
draft1.head()

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [18]:
draft1.head(100)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [19]:
draft1.tail()

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [20]:
draft1.tail(2)

   a   b   c   d message
1  5   6   7   8   world
2  9  10  11  12     foo

In [21]:
draft2=pd.read_table('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\test.tsv')
draft2

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [22]:
draft2=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\test.tsv')
draft2

              test\t test\ttest\ttest\ttest
0        sudh\tsudh\tsudh\tsudh\tsudh\tsudh
1  kumar\tkumar\tkumar\tkumar\tkumar\tkumar

In [23]:
draft2=pd.read_table('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\test.tsv')
draft2.head(100)

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [24]:
draft2.tail()

        test   test test.1 test.2 test.3
sudh    sudh   sudh   sudh   sudh   sudh
kumar  kumar  kumar  kumar  kumar  kumar

In [25]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [26]:
pd.read_table('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex1.csv')

  a,b,c,d,message
0   1,2,3,4,hello
1   5,6,7,8,world
2  9,10,11,12,foo

In [27]:
pd.read_table('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex1.csv',sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [28]:
pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex2.csv',header='infer')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [29]:
pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex2.csv',header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [30]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex2.csv',header='infer')
type(df)

pandas.core.frame.DataFrame

In [31]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex2.csv',header='infer',names=['abc','def','ghi','jkl','mno'])
df

   abc  def  ghi  jkl    mno
0    1    2    3    4  hello
1    5    6    7    8  world
2    9   10   11   12    foo

In [32]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex2.csv',header='infer',names=['abc','def','ghi','jkl','mno','xyz'])
df

   abc  def  ghi  jkl    mno  xyz
0    1    2    3    4  hello  NaN
1    5    6    7    8  world  NaN
2    9   10   11   12    foo  NaN

In [33]:
df1=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\csv_mindex.csv')
df1

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [34]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\csv_mindex.csv',index_col=['key1','key2'])
df

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [35]:
pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex4.csv')

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [36]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex4.csv',sep='\t')
df

                                              # hey!
0                                    a,b,c,d,message
1  # just wanted to make things more difficult fo...
2      # who reads CSV files with computers, anyway?
3                                      1,2,3,4,hello
4                                      5,6,7,8,world
5                                     9,10,11,12,foo

In [37]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex4.csv',skiprows=[0,2,3])
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [38]:
dir(pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex4.csv'))

['T',
 '_AXIS_ALIASES',
 '_AXIS_IALIASES',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_add_numeric_operations',
 '_add_series_or_dataframe_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_aggregate',
 '_aggregate_multiple_funcs',
 '_align_frame',
 '_align_series',
 '_box_col_values',
 '_box_item_values',
 '_builtin_table',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_combine_frame',
 '_combine_match_index',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_dict_from',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_create_indexer',
 '_cython_table',
 '_deprecations',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_type',
 '_ensure_valid_index',
 '_find_valid_index',
 '_from_arrays',
 '_from_axes',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_cython_func',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_iget_item_cache',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_internal_get_values',
 '_internal_names',
 '_internal_names_set',
 '_is_builtin_func',
 '_is_cached',
 '_is_copy',
 '_is_datelike_mixed_type',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_numeric_mixed_type',
 '_is_view',
 '_ix',
 '_ixs',
 '_join_compat',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_needs_reindex_multi',
 '_obj_with_exclusions',
 '_protect_consolidate',
 '_reduce',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_selected_obj',
 '_selection',
 '_selection_list',
 '_selection_name',
 '_series',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_is_copy',
 '_set_item',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_setup_axes',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_try_aggregate_string_function',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 '_xs',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'values',
 'var',
 'where',
 'xs']

In [39]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex5.csv')
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [40]:
pd.isnull(df)

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False,False,False

In [41]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [42]:
result=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex5.csv',na_values=['NULL'])
result

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [43]:
result=pd.read_excel('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\test1.xlsx')
result

   hloop       chu Unnamed: 2     bvjb Unnamed: 4 Unnamed: 5
0  bvnjc       NaN         fb      NaN        NaN    jfujhfg
1    NaN      bfhv       fbuh  jvfujfv   jbdjvuhv        NaN
2    NaN       NaN        NaN      NaN        NaN        NaN
3   hfuh  nfcjikfj      kmfik   nv jnv       fmji        NaN

In [44]:
result=pd.read_excel('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\test1.xlsx',sheet_name='Sheet2')
result

  nbvgbg Unnamed: 1  njvn  njvn.1   hnvj
0  cnjfh      bhgbv   NaN     NaN    NaN
1    NaN        NaN  lfmk     NaN  vnvhb
2   bjch       uhff   NaN  vjnfho    NaN

In [45]:
#result.head(12)
result.head(2)

  nbvgbg Unnamed: 1  njvn njvn.1   hnvj
0  cnjfh      bhgbv   NaN    NaN    NaN
1    NaN        NaN  lfmk    NaN  vnvhb

In [46]:
url='http://www.basketball-reference.com/leagues/NBA_2015_totals.html'
BB_data=pd.read_html(url)    #read from hte specified url
BB_data

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [47]:
#BB_data[0].iloc[:,20].head(10)  
df=BB_data[0]
df.head(10)   #check 5 rows 10 columns only

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
5,5,Arron Afflalo,SG,29,DEN,53,53,1750,281,657,...,.841,21,159,180,101,32,5,83,108,771
6,5,Arron Afflalo,SG,29,POR,25,19,752,94,227,...,.851,6,61,67,28,9,2,33,59,264
7,6,Alexis Ajinça,C,26,NOP,68,8,957,181,329,...,.818,104,211,315,47,21,51,69,151,443
8,7,Furkan Aldemir,PF,23,PHI,41,9,540,40,78,...,.481,78,98,176,28,17,16,17,96,93
9,8,Cole Aldrich,C,26,NYK,61,16,976,144,301,...,.781,101,237,338,75,37,65,59,122,338

In [48]:
df.tail(10)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
665,485,Brandan Wright,PF,27,PHO,40,7,858,120,207,...,.667,70,124,194,23,32,47,16,54,280
666,486,Dorell Wright,SF,29,POR,48,2,592,72,190,...,.810,14,97,111,41,20,11,18,55,219
667,487,Tony Wroten,PG,21,PHI,30,15,895,175,434,...,.667,22,64,86,157,48,8,113,72,507
668,488,James Young,SG,19,BOS,31,0,332,36,102,...,.552,9,33,42,13,8,2,5,22,105
669,489,Nick Young,SG,29,LAL,42,0,1000,174,476,...,.892,17,79,96,41,23,11,44,83,563
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [49]:
df['Player']

0          Quincy Acy
1        Jordan Adams
2        Steven Adams
3         Jeff Adrien
4       Arron Afflalo
            ...
670    Thaddeus Young
671    Thaddeus Young
672    Thaddeus Young
673       Cody Zeller
674      Tyler Zeller
Name: Player, Length: 675, dtype: object

In [50]:
df[['MP','ORB']]

       MP  ORB
0    1287   79
1     248    9
2    1771  199
3     215   23
4    2502   27
..    ...  ...
670  2434  127
671  1605   75
672   829   52
673  1487   97
674  1731  146

[675 rows x 2 columns]

In [51]:
df[['MP','TOV']]

       MP  TOV
0    1287   60
1     248   14
2    1771   99
3     215    9
4    2502  116
..    ...  ...
670  2434  117
671  1605   75
672   829   42
673  1487   62
674  1731   76

[675 rows x 2 columns]

In [52]:
df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [53]:
df[0:25]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
5,5,Arron Afflalo,SG,29,DEN,53,53,1750,281,657,...,.841,21,159,180,101,32,5,83,108,771
6,5,Arron Afflalo,SG,29,POR,25,19,752,94,227,...,.851,6,61,67,28,9,2,33,59,264
7,6,Alexis Ajinça,C,26,NOP,68,8,957,181,329,...,.818,104,211,315,47,21,51,69,151,443
8,7,Furkan Aldemir,PF,23,PHI,41,9,540,40,78,...,.481,78,98,176,28,17,16,17,96,93
9,8,Cole Aldrich,C,26,NYK,61,16,976,144,301,...,.781,101,237,338,75,37,65,59,122,338
10,9,LaMarcus Aldridge,PF,29,POR,71,71,2512,659,1415,...,.845,177,549,726,124,48,68,122,125,1661
11,10,Lavoy Allen,C,25,IND,63,0,1070,141,299,...,.702,123,200,323,73,15,42,40,102,315
12,11,Tony Allen,SG,33,MEM,63,41,1648,225,455,...,.627,103,177,280,86,129,30,86,166,539
13,12,Al-Farouq Aminu,SF,24,DAL,74,3,1366,147,357,...,.712,114,228,342,59,70,62,55,137,412
14,13,Lou Amundson,PF,32,TOT,53,35,937,109,255,...,.471,94,174,268,70,22,52,62,126,259
15,13,Lou Amundson,PF,32,CLE,12,0,79,4,12,...,.600,5,15,20,5,1,0,5,11,11
16,13,Lou Amundson,PF,32,NYK,41,35,858,105,243,...,.463,89,159,248,65,21,52,57,115,248
17,14,Chris Andersen,C,36,MIA,60,20,1132,120,207,...,.667,76,223,299,43,26,61,40,88,320
18,15,Alan Anderson,SG,32,BRK,74,19,1744,195,440,...,.812,31,173,204,83,56,5,60,148,545
19,16,Kyle Anderson,SF,21,SAS,33,8,358,31,89,...,.643,5,67,72,28,15,7,10,28,74
20,17,Ryan Anderson,PF,26,NOP,61,5,1675,291,729,...,.854,108,187,295,55,33,20,62,113,833
21,18,Giannis Antetokounmpo,SG,20,MIL,81,71,2541,383,780,...,.741,100,442,542,207,73,85,173,254,1030
22,19,Carmelo Anthony,SF,30,NYK,40,40,1428,358,806,...,.797,72,192,264,122,40,17,89,87,966
23,20,Joel Anthony,C,32,DET,49,0,406,36,62,...,.682,32,61,93,5,12,49,12,55,87
24,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS

In [54]:
df[['MP',"TOV"]].head()

     MP  TOV
0  1287   60
1   248   14
2  1771   99
3   215    9
4  2502  116

In [55]:
df.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [56]:
df

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [57]:
df['Player'].dtype

dtype('O')

In [58]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')

In [59]:
titanic_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [60]:
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [61]:
titanic_train[['Survived','Name']]

     Survived                                               Name
0           0                            Braund, Mr. Owen Harris
1           1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2           1                             Heikkinen, Miss. Laina
3           1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4           0                           Allen, Mr. William Henry
..        ...                                                ...
151         1                  Pears, Mrs. Thomas (Edith Wearne)
152         0                                   Meo, Mr. Alfonzo
153         0                    van Billiard, Mr. Austin Blyler
154         0                              Olsen, Mr. Ole Martin
155         0                        Williams, Mr. Charles Duane

[156 rows x 2 columns]

In [62]:
titanic_train[['Name','Pclass']]

                                                  Name  Pclass
0                              Braund, Mr. Owen Harris       3
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                               Heikkinen, Miss. Laina       3
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                             Allen, Mr. William Henry       3
..                                                 ...     ...
151                  Pears, Mrs. Thomas (Edith Wearne)       1
152                                   Meo, Mr. Alfonzo       3
153                    van Billiard, Mr. Austin Blyler       3
154                              Olsen, Mr. Ole Martin       3
155                        Williams, Mr. Charles Duane       1

[156 rows x 2 columns]

In [63]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [64]:
#TASK--1
"""
1.read data
2.print first 5 data
3.print last 2 data
4.give your own column name
5.select one column and print its data type
6.print datatype
7.check data if any data is null
8.skip random rows
"""

"""
##1.
link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 sep=';')
link
##2.
link.head()
##3.
link.tail(2)
##4.
link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 sep=';',names=['abc','def','gh','ij','kl','lm'])
link
##5.

#link['abc']
link['def'].dtypes
##6.
link.dtypes

##7.
link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 sep=';',na_values=['NULL'])
link
##8.
link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 sep=';',skiprows=[46,73,56])
link
"""


link=('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv')
pd.read_csv(link).head()

  age;"job";"marital";"education";"default";"housing";"loan";"contact";"month";"day_of_week";"duration";"campaign";"pdays";"previous";"poutcome";"emp.var.rate";"cons.price.idx";"cons.conf.idx";"euribor3m";"nr.employed";"y"
0  56;"housemaid";"married";"basic.4y";"no";"no";...
1  57;"services";"married";"high.school";"unknown...
2  37;"services";"married";"high.school";"no";"ye...
3  40;"admin.";"married";"basic.6y";"no";"no";"no...
4  56;"services";"married";"high.school";"no";"no...

In [65]:
##1.
link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 sep=';')
link

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [66]:
##2.
link.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [67]:
##3.
link.tail(2)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [68]:
df.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [69]:
##4.

#change the column name

link.rename(columns={"age":'Age'})
#link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 #sep=';',names=['abc','def','gh','ij','kl','lm'])
#link

,Age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [70]:
##5.

#link['abc']
link['age'].dtype

dtype('int64')

In [71]:
link['housing'].dtypes

dtype('O')

In [72]:
##6.
link.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [73]:
##7.
#link
link

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [74]:
#link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 #sep=';',na_values=['NULL'])
link.isnull()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41184,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41185,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41186,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41187,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [75]:
##8.
link=pd.read_csv('https://raw.githubusercontent.com/akhil12028/Bank-Marketing-data-set-analysis/master/bank-additional-full.csv',
                 sep=';',skiprows=[46,73,56])
link

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41180,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41181,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41182,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41183,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [76]:
#1.
link
link.dtypes

age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

# Doubt

In [77]:
import numpy as np
a=np.array((1,2,3))
a

array([1, 2, 3])

In [78]:
type(a)

numpy.ndarray

In [79]:
np.mat(((2,3,4),(5,6,7)))

matrix([[2, 3, 4],
        [5, 6, 7]])

In [80]:
np.matrix(((6,7,8),(4,5,6)))

matrix([[6, 7, 8],
        [4, 5, 6]])

In [81]:
np.mat(((2,3,4),(5,6,7.)))

matrix([[2., 3., 4.],
        [5., 6., 7.]])

In [82]:
np.mat(((2,.3,4),(5,6,7)))

matrix([[2. , 0.3, 4. ],
        [5. , 6. , 7. ]])

In [83]:
x=np.array(((1,2,3),(6,7,8)))
x

array([[1, 2, 3],
       [6, 7, 8]])

In [84]:
y=x
y

array([[1, 2, 3],
       [6, 7, 8]])

# Doubt End

In [85]:
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [86]:
titanic_train.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [87]:
titanic_train.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
146,147,1,3,"Andersson, Mr. August Edvard (""Wennerstrom"")",male,27.0,0,0,350043,7.7958,NaN,S
147,148,0,3,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S
148,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.5,0,2,230080,26.0000,F2,S
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.0,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

In [88]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [89]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [90]:
titanic_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,156.000000,156.000000,156.000000,126.000000,156.000000,156.000000,156.000000
mean,78.500000,0.346154,2.423077,28.141508,0.615385,0.397436,28.109587
std,45.177428,0.477275,0.795459,14.613880,1.056235,0.870146,39.401047
min,1.000000,0.000000,1.000000,0.830000,0.000000,0.000000,6.750000
25%,39.750000,0.000000,2.000000,19.000000,0.000000,0.000000,8.003150
50%,78.500000,0.000000,3.000000,26.000000,0.000000,0.000000,14.454200
75%,117.250000,1.000000,3.000000,35.000000,1.000000,0.000000,30.371850
max,156.000000,1.000000,3.000000,71.000000,5.000000,5.000000,263.000000

In [91]:
result=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [92]:
result.head(10)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q
5  1.817480  0.742273  0.419395 -2.251035   Q
6 -0.776764  0.935518 -0.332872 -1.875641   U
7 -0.913135  1.530624 -0.572657  0.477252   K
8  0.358480 -0.497572 -0.367016  0.507702   S
9 -1.740877 -1.160417 -1.637830  2.172201   G

In [93]:
result=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex6.csv',nrows=10)
result

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q
5  1.817480  0.742273  0.419395 -2.251035   Q
6 -0.776764  0.935518 -0.332872 -1.875641   U
7 -0.913135  1.530624 -0.572657  0.477252   K
8  0.358480 -0.497572 -0.367016  0.507702   S
9 -1.740877 -1.160417 -1.637830  2.172201   G

In [94]:
#Chunksize is always try to return the textfile
result=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex6.csv',chunksize=1000)

result

In [95]:
df=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex5.csv')
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [96]:
#For Read the pandas data we use---pd.read_csv('File name with path')
#For Write the pandas data we use3---pd.to_csv('file name with path')

In [97]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [98]:
df.to_csv('xyzz.csv')

In [99]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [100]:
data=df.to_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex5.csv')
data

In [101]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [102]:
df.to_csv('abcd.csv',sep='@')

In [103]:
import sys
df.to_csv(sys.stdout,na_rep='Tulsi')

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,Tulsi
1,1,1,1,1,two,5,6,Tulsi,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [104]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [105]:
df.to_csv('out1.csv')

In [106]:
df.to_csv('out1.csv',header=False)

In [107]:
df.to_csv('out1.csv',index=False,header=False)

In [108]:
df.to_csv('out2.csv',index=False,columns=['something','a','b','c'])

In [109]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Unnamed: 0.1.1.1,something,a,b,c,d,message
0,0,0,0,0,one,1,2,3.0,4,NaN
1,1,1,1,1,two,5,6,NaN,8,world
2,2,2,2,2,three,9,10,11.0,12,foo

In [110]:
dates=pd.date_range('1/1/2020',periods=70)
dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12',
               '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16',
               '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20',
               '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24',
               '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28',
               '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01',
               '2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05',
               '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09',
               '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13',
               '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17',
               '2020-02-18', '2020-02-19', '2020-02-20', '2020-02-21',
               '2020-02-22', '2020-02-23', '2020-02-24', '2020-02-25',
               '2020-02-26', '2020-02-27', '2020-02-28', '2020-02-29',
               '2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04',
               '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08',
               '2020-03-09', '2020-03-10'],
              dtype='datetime64[ns]', freq='D')

In [111]:
dates=pd.date_range('1/1/2020',periods=7)
dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07'],
              dtype='datetime64[ns]', freq='D')

In [112]:
ts=pd.Series(np.arange(7))
ts

0    0
1    1
2    2
3    3
4    4
5    5
6    6
dtype: int32

In [113]:
ts=pd.Series(np.arange(7),index=dates)
#ts=pd.Series(np.arange(7),index=['fnv','hu','dcnji','vb',78,'y',9+4j])
ts

2020-01-01    0
2020-01-02    1
2020-01-03    2
2020-01-04    3
2020-01-05    4
2020-01-06    5
2020-01-07    6
Freq: D, dtype: int32

In [114]:
ts.to_csv('heyyy.csv')

# working with delimited formate

In [115]:
import csv
f=open('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex7.csv')
f

reader=csv.reader(f)
#reader
list(reader)

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

In [116]:
list(reader)

[]

In [117]:
for line in reader:
    print(line)

In [118]:
with open() as f:
    lines=list(csv.reader(f))
lines

TypeError: open() missing required argument 'file' (pos 1)

In [ ]:
lines

In [ ]:
a=2
b=4.5
c=4+7j

In [ ]:
c

In [ ]:
a,b,c=2,4.5,4+7j

In [ ]:
c

In [ ]:
header,values=lines[0],lines[1:]

In [ ]:
lines[0]

In [ ]:
header

In [ ]:
values

In [ ]:
zip(values)

In [ ]:
list(zip(values))

In [ ]:
list(zip(*values))

In [ ]:
list(zip(header,zip(*values)))

In [ ]:
dict_data={h: v for h,v in zip(header,zip(*values))}
dict_data

In [ ]:
l1=[2,3,4,5]
l2=['a','b','c','d']
list(zip(l1,l2))

In [119]:
dict_data={h: v for h,v in zip(l1,zip(l2))}
dict_data

NameError: name 'l1' is not defined

In [120]:
{a:b for a,b in zip(l1,l2)}

NameError: name 'l1' is not defined

JSON DATA--(Java Script Object Notation)

In [121]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [122]:
#print(obj)
type(obj)

str

In [123]:
import json
result=json.loads(obj)
result
type(result)

dict

In [124]:
asjson=json.dumps(result)
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [125]:
type(asjson)

str

In [126]:
result['siblings']

[{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
 {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]

In [127]:
siblings=pd.DataFrame(result['siblings'],columns=['age','pets'])
siblings

   age                    pets
0   30            [Zeus, Zuko]
1   38  [Sixes, Stache, Cisco]

In [128]:
data=pd.read_json('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [129]:
data.to_json()

'{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}'

In [130]:
tables=pd.read_html('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\fdic_failed_bank_list.html')
tables

[                             Bank Name             City  ST   CERT  \
 0                          Allied Bank         Mulberry  AR     91
 1         The Woodbury Banking Company         Woodbury  GA  11297
 2               First CornerStone Bank  King of Prussia  PA  35312
 3                   Trust Company Bank          Memphis  TN   9956
 4           North Milwaukee State Bank        Milwaukee  WI  20364
 ..                                 ...              ...  ..    ...
 542                 Superior Bank, FSB         Hinsdale  IL  32646
 543                Malta National Bank            Malta  OH   6629
 544    First Alliance Bank & Trust Co.       Manchester  NH  34264
 545  National State Bank of Metropolis       Metropolis  IL   3815
 546                   Bank of Honolulu         Honolulu  HI  21029

                    Acquiring Institution        Closing Date  \
 0                           Today's Bank  September 23, 2016
 1                            United Bank     August 19, 2016
 2    First-Citizens Bank & Trust Company         May 6, 2016
 3             The Bank of Fayette County      April 29, 2016
 4    First-Citizens Bank & Trust Company      March 11, 2016
 ..                                   ...                 ...
 542                Superior Federal, FSB       July 27, 2001
 543                    North Valley Bank         May 3, 2001
 544  Southern New Hampshire Bank & Trust    February 2, 2001
 545              Banterra Bank of Marion   December 14, 2000
 546                   Bank of the Orient    October 13, 2000

           Updated Date
 0    November 17, 2016
 1    November 17, 2016
 2    September 6, 2016
 3    September 6, 2016
 4        June 16, 2016
 ..                 ...
 542    August 19, 2014
 543  November 18, 2002
 544  February 18, 2003
 545     March 17, 2005
 546     March 17, 2005

 [547 rows x 7 columns]]

In [131]:
type('tables')

str

In [132]:
len(tables)

1

In [133]:
tables[0]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"
...,...,...,...,...,...,...,...
542,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB","July 27, 2001","August 19, 2014"
543,Malta National Bank,Malta,OH,6629,North Valley Bank,"May 3, 2001","November 18, 2002"
544,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,"February 2, 2001","February 18, 2003"
545,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,"December 14, 2000","March 17, 2005"
546,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,"October 13, 2000","March 17, 2005"

In [134]:
tables[0:10]

[                             Bank Name             City  ST   CERT  \
 0                          Allied Bank         Mulberry  AR     91
 1         The Woodbury Banking Company         Woodbury  GA  11297
 2               First CornerStone Bank  King of Prussia  PA  35312
 3                   Trust Company Bank          Memphis  TN   9956
 4           North Milwaukee State Bank        Milwaukee  WI  20364
 ..                                 ...              ...  ..    ...
 542                 Superior Bank, FSB         Hinsdale  IL  32646
 543                Malta National Bank            Malta  OH   6629
 544    First Alliance Bank & Trust Co.       Manchester  NH  34264
 545  National State Bank of Metropolis       Metropolis  IL   3815
 546                   Bank of Honolulu         Honolulu  HI  21029

                    Acquiring Institution        Closing Date  \
 0                           Today's Bank  September 23, 2016
 1                            United Bank     August 19, 2016
 2    First-Citizens Bank & Trust Company         May 6, 2016
 3             The Bank of Fayette County      April 29, 2016
 4    First-Citizens Bank & Trust Company      March 11, 2016
 ..                                   ...                 ...
 542                Superior Federal, FSB       July 27, 2001
 543                    North Valley Bank         May 3, 2001
 544  Southern New Hampshire Bank & Trust    February 2, 2001
 545              Banterra Bank of Marion   December 14, 2000
 546                   Bank of the Orient    October 13, 2000

           Updated Date
 0    November 17, 2016
 1    November 17, 2016
 2    September 6, 2016
 3    September 6, 2016
 4        June 16, 2016
 ..                 ...
 542    August 19, 2014
 543  November 18, 2002
 544  February 18, 2003
 545     March 17, 2005
 546     March 17, 2005

 [547 rows x 7 columns]]

# Binary Data Formate

In [135]:
# object->bytecode=serde

In [136]:
frame=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [137]:
type(frame)

pandas.core.frame.DataFrame

In [138]:
frame.to_pickle('frame_pickle')

In [139]:
pwd()

'C:\\Users\\Raushan'

In [140]:
frame.to_pickle('frame_pickle')

In [141]:
pd.read_pickle('frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [142]:
frame=pd.read_csv('C:\\Users\\Raushan\\Downloads\\code_pandas1_2\\code_pandas1\\examples\\ex1.csv')
frame
type(frame)
frame.to_pickle('frame_pickle')
pd.read_pickle('frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [143]:
frame=pd.DataFrame({'a':np.random.randn(100)})
frame

           a
0  -0.340095
1  -0.328586
2   0.964550
3   0.906137
4  -0.960289
..       ...
95 -0.057466
96 -0.528432
97  0.076000
98 -1.029393
99  0.956022

[100 rows x 1 columns]

Another way to read the binary file

In [144]:
store=pd.HDFStore('mydata5.h5')
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata5.h5

In [145]:
store['obj1']=frame

In [146]:
store['obj1']

           a
0  -0.340095
1  -0.328586
2   0.964550
3   0.906137
4  -0.960289
..       ...
95 -0.057466
96 -0.528432
97  0.076000
98 -1.029393
99  0.956022

[100 rows x 1 columns]

In [147]:
store['obj1_col']=frame['a']

In [148]:
store['obj1_col']

0    -0.340095
1    -0.328586
2     0.964550
3     0.906137
4    -0.960289
        ...
95   -0.057466
96   -0.528432
97    0.076000
98   -1.029393
99    0.956022
Name: a, Length: 100, dtype: float64

In [149]:
frame=pd.DataFrame({'a':np.random.randn(100)})
frame
store=pd.HDFStore('mydata5.h5')
store
store['obj1']=frame
store['obj1_col']=frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata5.h5

# WEB API

In [150]:
import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
print(url)

https://api.github.com/repos/pandas-dev/pandas/issues

In [151]:
resp=requests.get(url)
resp

In [152]:
type(resp)

requests.models.Response

In [153]:
data=resp.json()
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35735',
  'id': 679530089,
  'node_id': 'MDU6SXNzdWU2Nzk1MzAwODk=',
  'number': 35735,
  'title': 'BUG: DataFrame.merge() fails with program termination, consumed entire available memory(Memory Leak)',
  'user': {'login': 'HimanshuS24',
   'id': 60599856,
   'node_id': 'MDQ6VXNlcjYwNTk5ODU2',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/60599856?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/HimanshuS24',
   'html_url': 'https://github.com/HimanshuS24',
   'followers_url': 'https://api.github.com/users/HimanshuS24/followers',
   'following_url': 'https://api.github.com/users/HimanshuS24/following{/other_user}',
   'gists_url': 'https://api.github.com/users/HimanshuS24/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/HimanshuS24/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/HimanshuS24/subscriptions',
   'organizations_url': 'https://api.github.com/users/HimanshuS24/orgs',
   'repos_url': 'https://api.github.com/users/HimanshuS24/repos',
   'events_url': 'https://api.github.com/users/HimanshuS24/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/HimanshuS24/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-15T09:02:11Z',
  'updated_at': '2020-08-15T09:02:21Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\n \r\ndf1 = pd.read_csv(path_of_csv1)\r\ndf2 = pd.read_csv(path_of_csv2)\r\nresultant_df = df1.merge(df2, left_on='left_csv_column_name', right_on='right_csv_column_name', how='inner') <= Exception thrown here.\r\n\r\n```\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Problem description\r\n\r\nMemory Leak occurs while trying to merge two Dataframes read from two different CSV's of bigger size (>=10Mb in my case)\r\n\r\nFor smaller CSV files (let's say of <=10Mb) each merging process is working fine. \r\nMy system is having 8Gb of RAM and before starting the Merging process, Enough Memory is available(>3Gb) and after starting the merging process, the system consumes the entire available memory and killed the merging process in between with the below exception:-\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Expected Output\r\n\r\n`resultant_df` contains the two DataFrame `df1` and `df2` based on the join type we have given as a parameter `how='inner'` in pandas merge function\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.4.0\r\nVersion          : Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.2.1\r\nsetuptools       : 49.2.1\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None]\r\n\r\n</details>\r\n",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35733',
  'id': 679437691,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDY4MjEyNTEz',
  'number': 35733,
  'title': 'BLD: update min versions #35732',
  'user': {'login': 'VirosaLi',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/VirosaLi',
   'html_url': 'https://github.com/VirosaLi',
   'followers_url': 'https://api.github.com/users/VirosaLi/followers',
   'following_url': 'https://api.github.com/users/VirosaLi/following{/other_user}',
   'gists_url': 'https://api.github.com/users/VirosaLi/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/VirosaLi/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/VirosaLi/subscriptions',
   'organizations_url': 'https://api.github.com/users/VirosaLi/orgs',
   'repos_url': 'https://api.github.com/users/VirosaLi/repos',
   'events_url': 'https://api.github.com/users/VirosaLi/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/VirosaLi/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T22:45:03Z',
  'updated_at': '2020-08-14T22:45:06Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35733',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35733',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35733.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35733.patch'},
  'body': '- [x] closes #35732\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35732',
  'id': 679434758,
  'node_id': 'MDU6SXNzdWU2Nzk0MzQ3NTg=',
  'number': 35732,
  'title': 'BLD: minimum versions need update in `pandas/compat/_optional.py`',
  'user': {'login': 'VirosaLi',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/VirosaLi',
   'html_url': 'https://github.com/VirosaLi',
   'followers_url': 'https://api.github.com/users/VirosaLi/followers',
   'following_url': 'https://api.github.com/users/VirosaLi/following{/other_user}',
   'gists_url': 'https://api.github.com/users/VirosaLi/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/VirosaLi/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/VirosaLi/subscriptions',
   'organizations_url': 'https://api.github.com/users/VirosaLi/orgs',
   'repos_url': 'https://api.github.com/users/VirosaLi/repos',
   'events_url': 'https://api.github.com/users/VirosaLi/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/VirosaLi/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T22:34:13Z',
  'updated_at': '2020-08-14T22:34:13Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': 'The minimum versions in `pandas/compat/_optional.py` were not updated in #35214.',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35731',
  'id': 679421423,
  'node_id': 'MDU6SXNzdWU2Nzk0MjE0MjM=',
  'number': 35731,
  'title': 'BUG: Series has no attribute "reshape" after adding a new category in df',
  'user': {'login': 'chen-bowen',
   'id': 18410378,
   'node_id': 'MDQ6VXNlcjE4NDEwMzc4',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/18410378?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/chen-bowen',
   'html_url': 'https://github.com/chen-bowen',
   'followers_url': 'https://api.github.com/users/chen-bowen/followers',
   'following_url': 'https://api.github.com/users/chen-bowen/following{/other_user}',
   'gists_url': 'https://api.github.com/users/chen-bowen/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/chen-bowen/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/chen-bowen/subscriptions',
   'organizations_url': 'https://api.github.com/users/chen-bowen/orgs',
   'repos_url': 'https://api.github.com/users/chen-bowen/repos',
   'events_url': 'https://api.github.com/users/chen-bowen/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/chen-bowen/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T21:55:57Z',
  'updated_at': '2020-08-14T21:59:50Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,

In [154]:
data[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/events',
 'html_url': 'https://github.com/pandas-dev/pandas/issues/35735',
 'id': 679530089,
 'node_id': 'MDU6SXNzdWU2Nzk1MzAwODk=',
 'number': 35735,
 'title': 'BUG: DataFrame.merge() fails with program termination, consumed entire available memory(Memory Leak)',
 'user': {'login': 'HimanshuS24',
  'id': 60599856,
  'node_id': 'MDQ6VXNlcjYwNTk5ODU2',
  'avatar_url': 'https://avatars0.githubusercontent.com/u/60599856?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/HimanshuS24',
  'html_url': 'https://github.com/HimanshuS24',
  'followers_url': 'https://api.github.com/users/HimanshuS24/followers',
  'following_url': 'https://api.github.com/users/HimanshuS24/following{/other_user}',
  'gists_url': 'https://api.github.com/users/HimanshuS24/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/HimanshuS24/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/HimanshuS24/subscriptions',
  'organizations_url': 'https://api.github.com/users/HimanshuS24/orgs',
  'repos_url': 'https://api.github.com/users/HimanshuS24/repos',
  'events_url': 'https://api.github.com/users/HimanshuS24/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/HimanshuS24/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [{'id': 76811,
   'node_id': 'MDU6TGFiZWw3NjgxMQ==',
   'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
   'name': 'Bug',
   'color': 'e10c02',
   'default': False,
   'description': None},
  {'id': 1954720290,
   'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
   'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
   'name': 'Needs Triage',
   'color': '0052cc',
   'default': False,
   'description': 'Issue that has not been reviewed by a pandas team member'}],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2020-08-15T09:02:11Z',
 'updated_at': '2020-08-15T09:02:21Z',
 'closed_at': None,
 'author_association': 'NONE',
 'active_lock_reason': None,
 'body': "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\n \r\ndf1 = pd.read_csv(path_of_csv1)\r\ndf2 = pd.read_csv(path_of_csv2)\r\nresultant_df = df1.merge(df2, left_on='left_csv_column_name', right_on='right_csv_column_name', how='inner') <= Exception thrown here.\r\n\r\n```\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Problem description\r\n\r\nMemory Leak occurs while trying to merge two Dataframes read from two different CSV's of bigger size (>=10Mb in my case)\r\n\r\nFor smaller CSV files (let's say of <=10Mb) each merging process is working fine. \r\nMy system is having 8Gb of RAM and before starting the Merging process, Enough Memory is available(>3Gb) and after starting the merging process, the system consumes the entire available memory and killed the merging process in between with the below exception:-\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Expected Output\r\n\r\n`resultant_df` contains the two DataFrame `df1` and `df2` based on the join type we have given as a parameter `how='inner'` in pandas merge function\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.4.0\r\nVersion          : Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.2.1\r\nsetuptools       : 49.2.1\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None]\r\n\r\n</details>\r\n",
 'performed_via_github_app': None}

In [155]:
#data['user']
data[0]['user']

{'login': 'HimanshuS24',
 'id': 60599856,
 'node_id': 'MDQ6VXNlcjYwNTk5ODU2',
 'avatar_url': 'https://avatars0.githubusercontent.com/u/60599856?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/HimanshuS24',
 'html_url': 'https://github.com/HimanshuS24',
 'followers_url': 'https://api.github.com/users/HimanshuS24/followers',
 'following_url': 'https://api.github.com/users/HimanshuS24/following{/other_user}',
 'gists_url': 'https://api.github.com/users/HimanshuS24/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/HimanshuS24/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/HimanshuS24/subscriptions',
 'organizations_url': 'https://api.github.com/users/HimanshuS24/orgs',
 'repos_url': 'https://api.github.com/users/HimanshuS24/repos',
 'events_url': 'https://api.github.com/users/HimanshuS24/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/HimanshuS24/received_events',
 'type': 'User',
 'site_admin': False}

In [156]:
data[0]['user']['id']

60599856

In [157]:
l=[]
for i in range(len(data)):
    l.append(data[0]['user']['id'])
l

[60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856,
 60599856]

In [158]:
data

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35735',
  'id': 679530089,
  'node_id': 'MDU6SXNzdWU2Nzk1MzAwODk=',
  'number': 35735,
  'title': 'BUG: DataFrame.merge() fails with program termination, consumed entire available memory(Memory Leak)',
  'user': {'login': 'HimanshuS24',
   'id': 60599856,
   'node_id': 'MDQ6VXNlcjYwNTk5ODU2',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/60599856?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/HimanshuS24',
   'html_url': 'https://github.com/HimanshuS24',
   'followers_url': 'https://api.github.com/users/HimanshuS24/followers',
   'following_url': 'https://api.github.com/users/HimanshuS24/following{/other_user}',
   'gists_url': 'https://api.github.com/users/HimanshuS24/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/HimanshuS24/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/HimanshuS24/subscriptions',
   'organizations_url': 'https://api.github.com/users/HimanshuS24/orgs',
   'repos_url': 'https://api.github.com/users/HimanshuS24/repos',
   'events_url': 'https://api.github.com/users/HimanshuS24/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/HimanshuS24/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-15T09:02:11Z',
  'updated_at': '2020-08-15T09:02:21Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\n \r\ndf1 = pd.read_csv(path_of_csv1)\r\ndf2 = pd.read_csv(path_of_csv2)\r\nresultant_df = df1.merge(df2, left_on='left_csv_column_name', right_on='right_csv_column_name', how='inner') <= Exception thrown here.\r\n\r\n```\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Problem description\r\n\r\nMemory Leak occurs while trying to merge two Dataframes read from two different CSV's of bigger size (>=10Mb in my case)\r\n\r\nFor smaller CSV files (let's say of <=10Mb) each merging process is working fine. \r\nMy system is having 8Gb of RAM and before starting the Merging process, Enough Memory is available(>3Gb) and after starting the merging process, the system consumes the entire available memory and killed the merging process in between with the below exception:-\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Expected Output\r\n\r\n`resultant_df` contains the two DataFrame `df1` and `df2` based on the join type we have given as a parameter `how='inner'` in pandas merge function\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.4.0\r\nVersion          : Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.2.1\r\nsetuptools       : 49.2.1\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None]\r\n\r\n</details>\r\n",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35733',
  'id': 679437691,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDY4MjEyNTEz',
  'number': 35733,
  'title': 'BLD: update min versions #35732',
  'user': {'login': 'VirosaLi',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/VirosaLi',
   'html_url': 'https://github.com/VirosaLi',
   'followers_url': 'https://api.github.com/users/VirosaLi/followers',
   'following_url': 'https://api.github.com/users/VirosaLi/following{/other_user}',
   'gists_url': 'https://api.github.com/users/VirosaLi/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/VirosaLi/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/VirosaLi/subscriptions',
   'organizations_url': 'https://api.github.com/users/VirosaLi/orgs',
   'repos_url': 'https://api.github.com/users/VirosaLi/repos',
   'events_url': 'https://api.github.com/users/VirosaLi/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/VirosaLi/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T22:45:03Z',
  'updated_at': '2020-08-14T22:45:06Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35733',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35733',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35733.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35733.patch'},
  'body': '- [x] closes #35732\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35732',
  'id': 679434758,
  'node_id': 'MDU6SXNzdWU2Nzk0MzQ3NTg=',
  'number': 35732,
  'title': 'BLD: minimum versions need update in `pandas/compat/_optional.py`',
  'user': {'login': 'VirosaLi',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/VirosaLi',
   'html_url': 'https://github.com/VirosaLi',
   'followers_url': 'https://api.github.com/users/VirosaLi/followers',
   'following_url': 'https://api.github.com/users/VirosaLi/following{/other_user}',
   'gists_url': 'https://api.github.com/users/VirosaLi/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/VirosaLi/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/VirosaLi/subscriptions',
   'organizations_url': 'https://api.github.com/users/VirosaLi/orgs',
   'repos_url': 'https://api.github.com/users/VirosaLi/repos',
   'events_url': 'https://api.github.com/users/VirosaLi/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/VirosaLi/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T22:34:13Z',
  'updated_at': '2020-08-14T22:34:13Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': 'The minimum versions in `pandas/compat/_optional.py` were not updated in #35214.',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35731',
  'id': 679421423,
  'node_id': 'MDU6SXNzdWU2Nzk0MjE0MjM=',
  'number': 35731,
  'title': 'BUG: Series has no attribute "reshape" after adding a new category in df',
  'user': {'login': 'chen-bowen',
   'id': 18410378,
   'node_id': 'MDQ6VXNlcjE4NDEwMzc4',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/18410378?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/chen-bowen',
   'html_url': 'https://github.com/chen-bowen',
   'followers_url': 'https://api.github.com/users/chen-bowen/followers',
   'following_url': 'https://api.github.com/users/chen-bowen/following{/other_user}',
   'gists_url': 'https://api.github.com/users/chen-bowen/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/chen-bowen/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/chen-bowen/subscriptions',
   'organizations_url': 'https://api.github.com/users/chen-bowen/orgs',
   'repos_url': 'https://api.github.com/users/chen-bowen/repos',
   'events_url': 'https://api.github.com/users/chen-bowen/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/chen-bowen/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T21:55:57Z',
  'updated_at': '2020-08-14T21:59:50Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,

In [159]:
data.columns

AttributeError: 'list' object has no attribute 'columns'

In [ ]:
dataa=pd.DataFrame(data,columns=['number','title','labels','state'])
dataa

In [ ]:
dataa.columns

In [ ]:
import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
print(url)
reps=requests.get(url)
reps

In [160]:
reps=requests.get(url)
reps

In [167]:
d1=reps.json()
d1

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35735/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35735',
  'id': 679530089,
  'node_id': 'MDU6SXNzdWU2Nzk1MzAwODk=',
  'number': 35735,
  'title': 'BUG: DataFrame.merge() fails with program termination, consumed entire available memory(Memory Leak)',
  'user': {'login': 'HimanshuS24',
   'id': 60599856,
   'node_id': 'MDQ6VXNlcjYwNTk5ODU2',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/60599856?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/HimanshuS24',
   'html_url': 'https://github.com/HimanshuS24',
   'followers_url': 'https://api.github.com/users/HimanshuS24/followers',
   'following_url': 'https://api.github.com/users/HimanshuS24/following{/other_user}',
   'gists_url': 'https://api.github.com/users/HimanshuS24/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/HimanshuS24/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/HimanshuS24/subscriptions',
   'organizations_url': 'https://api.github.com/users/HimanshuS24/orgs',
   'repos_url': 'https://api.github.com/users/HimanshuS24/repos',
   'events_url': 'https://api.github.com/users/HimanshuS24/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/HimanshuS24/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-15T09:02:11Z',
  'updated_at': '2020-08-15T09:02:21Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "- [x] I have checked that this issue has not already been reported.\r\n\r\n- [x] I have confirmed this bug exists on the latest version of pandas.\r\n\r\n- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.\r\n\r\n---\r\n\r\n**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.\r\n\r\n#### Code Sample, a copy-pastable example\r\n\r\n```python\r\nimport pandas as pd\r\n \r\ndf1 = pd.read_csv(path_of_csv1)\r\ndf2 = pd.read_csv(path_of_csv2)\r\nresultant_df = df1.merge(df2, left_on='left_csv_column_name', right_on='right_csv_column_name', how='inner') <= Exception thrown here.\r\n\r\n```\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Problem description\r\n\r\nMemory Leak occurs while trying to merge two Dataframes read from two different CSV's of bigger size (>=10Mb in my case)\r\n\r\nFor smaller CSV files (let's say of <=10Mb) each merging process is working fine. \r\nMy system is having 8Gb of RAM and before starting the Merging process, Enough Memory is available(>3Gb) and after starting the merging process, the system consumes the entire available memory and killed the merging process in between with the below exception:-\r\n\r\n```\r\n[1] 31330 killed python\r\n```\r\n\r\n#### Expected Output\r\n\r\n`resultant_df` contains the two DataFrame `df1` and `df2` based on the join type we have given as a parameter `how='inner'` in pandas merge function\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : None\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 19.4.0\r\nVersion          : Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : None.UTF-8\r\n\r\npandas           : 1.1.0\r\nnumpy            : 1.19.1\r\npytz             : 2020.1\r\ndateutil         : 2.8.1\r\npip              : 20.2.1\r\nsetuptools       : 49.2.1\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : None\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npytables         : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None]\r\n\r\n</details>\r\n",
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35733/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/35733',
  'id': 679437691,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0NDY4MjEyNTEz',
  'number': 35733,
  'title': 'BLD: update min versions #35732',
  'user': {'login': 'VirosaLi',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/VirosaLi',
   'html_url': 'https://github.com/VirosaLi',
   'followers_url': 'https://api.github.com/users/VirosaLi/followers',
   'following_url': 'https://api.github.com/users/VirosaLi/following{/other_user}',
   'gists_url': 'https://api.github.com/users/VirosaLi/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/VirosaLi/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/VirosaLi/subscriptions',
   'organizations_url': 'https://api.github.com/users/VirosaLi/orgs',
   'repos_url': 'https://api.github.com/users/VirosaLi/repos',
   'events_url': 'https://api.github.com/users/VirosaLi/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/VirosaLi/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T22:45:03Z',
  'updated_at': '2020-08-14T22:45:06Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/35733',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/35733',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/35733.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/35733.patch'},
  'body': '- [x] closes #35732\r\n',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35732/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35732',
  'id': 679434758,
  'node_id': 'MDU6SXNzdWU2Nzk0MzQ3NTg=',
  'number': 35732,
  'title': 'BLD: minimum versions need update in `pandas/compat/_optional.py`',
  'user': {'login': 'VirosaLi',
   'id': 7614606,
   'node_id': 'MDQ6VXNlcjc2MTQ2MDY=',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/7614606?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/VirosaLi',
   'html_url': 'https://github.com/VirosaLi',
   'followers_url': 'https://api.github.com/users/VirosaLi/followers',
   'following_url': 'https://api.github.com/users/VirosaLi/following{/other_user}',
   'gists_url': 'https://api.github.com/users/VirosaLi/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/VirosaLi/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/VirosaLi/subscriptions',
   'organizations_url': 'https://api.github.com/users/VirosaLi/orgs',
   'repos_url': 'https://api.github.com/users/VirosaLi/repos',
   'events_url': 'https://api.github.com/users/VirosaLi/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/VirosaLi/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T22:34:13Z',
  'updated_at': '2020-08-14T22:34:13Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': 'The minimum versions in `pandas/compat/_optional.py` were not updated in #35214.',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/35731/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/35731',
  'id': 679421423,
  'node_id': 'MDU6SXNzdWU2Nzk0MjE0MjM=',
  'number': 35731,
  'title': 'BUG: Series has no attribute "reshape" after adding a new category in df',
  'user': {'login': 'chen-bowen',
   'id': 18410378,
   'node_id': 'MDQ6VXNlcjE4NDEwMzc4',
   'avatar_url': 'https://avatars3.githubusercontent.com/u/18410378?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/chen-bowen',
   'html_url': 'https://github.com/chen-bowen',
   'followers_url': 'https://api.github.com/users/chen-bowen/followers',
   'following_url': 'https://api.github.com/users/chen-bowen/following{/other_user}',
   'gists_url': 'https://api.github.com/users/chen-bowen/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/chen-bowen/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/chen-bowen/subscriptions',
   'organizations_url': 'https://api.github.com/users/chen-bowen/orgs',
   'repos_url': 'https://api.github.com/users/chen-bowen/repos',
   'events_url': 'https://api.github.com/users/chen-bowen/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/chen-bowen/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-08-14T21:55:57Z',
  'updated_at': '2020-08-14T21:59:50Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,

In [ ]:
#TASKKKK
import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
print(url)
reps=requests.get(url)
reps
d1=reps.json()
d1
DF=pd.DataFrame(columns=['id','node_id','color','default','url','description','url','name'])
#DF
for i in range(30):
    d=pd.DataFrame(d1[i]['labels'],columns=['id','node_id','color','default','url','description','url','name'])
    DF=DF.append(d,ignore_index=True)
DF

In [169]:
DF=pd.DataFrame(columns=['id','node_id','color','default','url','description','url','name'])
#DF
for i in range(30):
    d=pd.DataFrame(d1[i]['labels'],columns=['id','node_id','color','default','url','description','url','name'])
    DF=DF.append(d,ignore_index=True)
DF

,id,node_id,color,default,url,description,url,name
0,76811,MDU6TGFiZWw3NjgxMQ==,e10c02,False,https://api.github.com/repos/pandas-dev/pandas...,None,https://api.github.com/repos/pandas-dev/pandas...,Bug
1,1954720290,MDU6TGFiZWwxOTU0NzIwMjkw,0052cc,False,https://api.github.com/repos/pandas-dev/pandas...,Issue that has not been reviewed by a pandas t...,https://api.github.com/repos/pandas-dev/pandas...,Needs Triage
2,76811,MDU6TGFiZWw3NjgxMQ==,e10c02,False,https://api.github.com/repos/pandas-dev/pandas...,None,https://api.github.com/repos/pandas-dev/pandas...,Bug
3,1954720290,MDU6TGFiZWwxOTU0NzIwMjkw,0052cc,False,https://api.github.com/repos/pandas-dev/pandas...,Issue that has not been reviewed by a pandas t...,https://api.github.com/repos/pandas-dev/pandas...,Needs Triage
4,76811,MDU6TGFiZWw3NjgxMQ==,e10c02,False,https://api.github.com/repos/pandas-dev/pandas...,None,https://api.github.com/repos/pandas-dev/pandas...,Bug
...,...,...,...,...,...,...,...,...
58,76865106,MDU6TGFiZWw3Njg2NTEwNg==,0052cc,False,https://api.github.com/repos/pandas-dev/pandas...,Related to pandas compatibility with other lib...,https://api.github.com/repos/pandas-dev/pandas...,Compat
59,57351315,MDU6TGFiZWw1NzM1MTMxNQ==,0052cc,False,https://api.github.com/repos/pandas-dev/pandas...,pandas-gbq compatability,https://api.github.com/repos/pandas-dev/pandas...,IO Google
60,76811,MDU6TGFiZWw3NjgxMQ==,e10c02,False,https://api.github.com/repos/pandas-dev/pandas...,None,https://api.github.com/repos/pandas-dev/pandas...,Bug
61,32815646,MDU6TGFiZWwzMjgxNTY0Ng==,e11d21,False,https://api.github.com/repos/pandas-dev/pandas...,Functionality that used to work in a prior pan...,https://api.github.com/repos/pandas-dev/pandas...,Regression
62,57522093,MDU6TGFiZWw1NzUyMjA5Mw==,5319e7,False,https://api.github.com/repos/pandas-dev/pandas...,String extension data type and string data,https://api.github.com/repos/pandas-dev/pandas...,Strings

In [171]:
'''import requests
url='https://api.github.com/repos/pandas-dev/pandas/issues'
reps=requests.get(url)
reps
d1=reps.json()
d1
df=pd.DataFrame(d1,column=['labels'])
x=[]
for i in range(len(df)):
    if ['labels'][i]==0:
        y={'id':'',
           'node_id':'',
           'name':'',
           'color':'',
           'default':'',
           'description':'',}
        x.append(y)
'''

"import requests\nurl='https://api.github.com/repos/pandas-dev/pandas/issues'\nreps=requests.get(url)\nreps\nd1=reps.json()\nd1\ndf=pd.DataFrame(d1,column=['labels'])\nx=[]\nfor i in range(len(df)):\n    if ['labels'][i]==0:\n        y={'id':'',\n           'node_id':'',\n           'name':'',\n           'color':'',\n           'default':'',\n           'description':'',}\n        x.append(y)\n"

In [163]:
import os.path
import pandas as pd
import numpy as np
import tabula as tb

def file_check():
    path1 = os.path.exists('/home/rohanoxob/JupyterPractice/Parent/Child1/PlanetTable.txt')
    path2 = os.path.exists('/home/rohanoxob/JupyterPractice/Parent/Child2/2018_Bookmatter_PlanetaryGeology.pdf')
    if path1 == True:
        df1 = pd.read_csv('/home/rohanoxob/JupyterPractice/Parent/Child1/PlanetTable.txt',sep = '\t')
        return df1
    if path2 == True:
        data = tb.read_pdf('/home/rohanoxob/JupyterPractice/Parent/Child2/2018_Bookmatter_PlanetaryGeology.pdf',pages = 10)
        df2 = data[0]
        return df2
    if path1 == False or path2 == False:
        print("Sorry file not found")

ModuleNotFoundError: No module named 'tabula'

In [164]:
import pandas as pd
from numpy import randn as rn

l1=['A',"A",'A',"B","B","B","C","C","C"]
l2=[1,2,3,1,2,3,1,2,3]
l3=[1,2,3,4,5,6,7,8,9]
L=list(zip(l1,l2,l3))
L
df1=pd.DataFrame(data=np.round(rn(9,3)),index=h,columns=['A','B','C'])
df1

ImportError: cannot import name 'randn' from 'numpy' (C:\Users\Raushan\anaconda3\lib\site-packages\numpy\__init__.py)